services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./reports:/app/reports
  

  drift-monitor:
    build: .
    command: python drift_monitor.py
    ports:
      - "8001:8001"
    volumes:
      - ./reports:/app/reports
 

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./evaluate_model.py:/opt/airflow/evaluate_model.py
      - ./minimal_retraining.py:/opt/airflow/minimal_retraining.py
      - ./data:/opt/airflow/data
      - ./inference.py:/opt/airflow/inference.py
      - ./model:/opt/airflow/model
    command: standalone