services:
  api:
    build: .
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  drift-monitor:
    build: .
    command: python drift_monitor.py
    volumes:
      - ./reports:/app/reports
    dns:
      - 8.8.8.8
      - 8.8.4.4

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    dns:
      - 8.8.8.8
      - 8.8.4.4